"""Create final paper-friendly BridgePRAG figures and metric tables.

This script is intentionally a post-processing layer.  It does not re-run
model inference; it reads the epoch-wise comparison CSV generated by
``plot_epoch_performance.py`` plus the two training logs, then writes a small
set of presentation/paper artifacts:

* epoch_accuracy.png: Accuracy over epochs, where accuracy is the required
  answer hit rate used by the PRAG evaluator.
* epoch_loss.png: epoch-averaged training objective on a log y-axis.
* final_metrics_table.csv/.md/.png: final-epoch metric table.
* best_metrics_table.csv/.md/.png: best-accuracy metric table.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import tempfile
from collections import defaultdict
from pathlib import Path
from typing import Iterable


COLORS = {"qp": "#2f5f9f", "ponly": "#c66a2e"}
LABELS = {"qp": "Question+Passage", "ponly": "Passage-only"}


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def as_float(row: dict[str, str], key: str, default: float = 0.0) -> float:
    try:
        return float(row.get(key, default))
    except (TypeError, ValueError):
        return default


def as_int(row: dict[str, str], key: str, default: int = 0) -> int:
    try:
        return int(float(row.get(key, default)))
    except (TypeError, ValueError):
        return default


def write_csv(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def write_markdown_table(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "| " + " | ".join(fieldnames) + " |",
        "| " + " | ".join(["---"] * len(fieldnames)) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(row.get(key, "")) for key in fieldnames) + " |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def epoch_metric_rows(rows: list[dict[str, str]]) -> list[dict]:
    out: list[dict] = []
    for row in rows:
        epoch = as_int(row, "epoch")
        qp_hit = as_float(row, "qp_mergeprag_hit")
        ponly_hit = as_float(row, "ponly_mergeprag_hit")
        out.append(
            {
                "epoch": epoch,
                "qp_accuracy": qp_hit,
                "ponly_accuracy": ponly_hit,
                "delta_accuracy": qp_hit - ponly_hit,
                "qp_token_precision": as_float(row, "qp_token_precision"),
                "ponly_token_precision": as_float(row, "ponly_token_precision"),
                "delta_token_precision": as_float(row, "delta_token_precision"),
                "qp_token_recall": as_float(row, "qp_token_recall"),
                "ponly_token_recall": as_float(row, "ponly_token_recall"),
                "delta_token_recall": as_float(row, "delta_token_recall"),
                "qp_token_f1": as_float(row, "qp_token_f1"),
                "ponly_token_f1": as_float(row, "ponly_token_f1"),
                "delta_token_f1": as_float(row, "delta_token_f1"),
                "qp_hit": qp_hit,
                "ponly_hit": ponly_hit,
                "delta_hit": qp_hit - ponly_hit,
                "qp_qa_score": as_float(row, "qp_qa_score"),
                "ponly_qa_score": as_float(row, "ponly_qa_score"),
                "delta_qa_score": as_float(row, "delta_qa_score"),
                "qp_time_s": as_float(row, "qp_time_s"),
                "ponly_time_s": as_float(row, "ponly_time_s"),
            }
        )
    return out


def fmt_pct(value: float) -> str:
    return f"{100.0 * value:.2f}"


def fmt_float(value: float) -> str:
    return f"{value:.3f}"


def table_rows_for_epoch(rows: list[dict], epoch: int) -> list[dict]:
    row = next(r for r in rows if int(r["epoch"]) == int(epoch))
    return [
        {
            "Model": LABELS["qp"],
            "Epoch": epoch,
            "Accuracy (%)": fmt_pct(row["qp_accuracy"]),
            "Precision (%)": fmt_pct(row["qp_token_precision"]),
            "Recall (%)": fmt_pct(row["qp_token_recall"]),
            "Token F1 (%)": fmt_pct(row["qp_token_f1"]),
            "Hit (%)": fmt_pct(row["qp_hit"]),
            "QA Score (%)": fmt_pct(row["qp_qa_score"]),
            "Avg. Time (s)": fmt_float(row["qp_time_s"]),
        },
        {
            "Model": LABELS["ponly"],
            "Epoch": epoch,
            "Accuracy (%)": fmt_pct(row["ponly_accuracy"]),
            "Precision (%)": fmt_pct(row["ponly_token_precision"]),
            "Recall (%)": fmt_pct(row["ponly_token_recall"]),
            "Token F1 (%)": fmt_pct(row["ponly_token_f1"]),
            "Hit (%)": fmt_pct(row["ponly_hit"]),
            "QA Score (%)": fmt_pct(row["ponly_qa_score"]),
            "Avg. Time (s)": fmt_float(row["ponly_time_s"]),
        },
    ]


def best_table_rows(rows: list[dict]) -> list[dict]:
    qp_best = max(rows, key=lambda r: (r["qp_accuracy"], r["qp_token_f1"]))
    ponly_best = max(rows, key=lambda r: (r["ponly_accuracy"], r["ponly_token_f1"]))
    return [
        {
            "Model": LABELS["qp"],
            "Best Epoch": int(qp_best["epoch"]),
            "Accuracy (%)": fmt_pct(qp_best["qp_accuracy"]),
            "Precision (%)": fmt_pct(qp_best["qp_token_precision"]),
            "Recall (%)": fmt_pct(qp_best["qp_token_recall"]),
            "Token F1 (%)": fmt_pct(qp_best["qp_token_f1"]),
            "Hit (%)": fmt_pct(qp_best["qp_hit"]),
            "QA Score (%)": fmt_pct(qp_best["qp_qa_score"]),
            "Avg. Time (s)": fmt_float(qp_best["qp_time_s"]),
        },
        {
            "Model": LABELS["ponly"],
            "Best Epoch": int(ponly_best["epoch"]),
            "Accuracy (%)": fmt_pct(ponly_best["ponly_accuracy"]),
            "Precision (%)": fmt_pct(ponly_best["ponly_token_precision"]),
            "Recall (%)": fmt_pct(ponly_best["ponly_token_recall"]),
            "Token F1 (%)": fmt_pct(ponly_best["ponly_token_f1"]),
            "Hit (%)": fmt_pct(ponly_best["ponly_hit"]),
            "QA Score (%)": fmt_pct(ponly_best["ponly_qa_score"]),
            "Avg. Time (s)": fmt_float(ponly_best["ponly_time_s"]),
        },
    ]


def read_json(path: Path) -> dict:
    if not str(path) or not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def epoch_loss_rows(path: Path, *, max_epochs: int | None = None) -> list[dict]:
    data = read_json(path)
    if not data:
        return []
    schedule = data.get("training_schedule") or {}
    steps_per_epoch = int(schedule.get("steps_per_epoch") or max(1, int(data.get("final_step") or 1)))
    buckets: dict[int, list[float]] = defaultdict(list)
    for item in data.get("step_losses") or []:
        step = item.get("step")
        objective = item.get("objective")
        if step is None or objective is None:
            continue
        epoch = max(1, int(math.ceil(float(step) / float(steps_per_epoch))))
        if max_epochs is not None:
            epoch = min(epoch, max_epochs)
        buckets[epoch].append(float(objective))
    return [
        {
            "epoch": epoch,
            "loss": sum(values) / len(values),
            "count": len(values),
        }
        for epoch, values in sorted(buckets.items())
        if values
    ]


def merged_loss_rows(qp_log: Path, ponly_log: Path, *, max_epochs: int | None = None) -> list[dict]:
    qp = {row["epoch"]: row for row in epoch_loss_rows(qp_log, max_epochs=max_epochs)}
    ponly = {row["epoch"]: row for row in epoch_loss_rows(ponly_log, max_epochs=max_epochs)}
    epochs = sorted(set(qp) | set(ponly))
    return [
        {
            "epoch": epoch,
            "qp_loss": qp.get(epoch, {}).get("loss", ""),
            "ponly_loss": ponly.get(epoch, {}).get("loss", ""),
            "qp_count": qp.get(epoch, {}).get("count", ""),
            "ponly_count": ponly.get(epoch, {}).get("count", ""),
        }
        for epoch in epochs
    ]


def import_pyplot():
    os.environ.setdefault("MPLCONFIGDIR", tempfile.mkdtemp(prefix="prag_mplconfig_"))
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    return plt


def style_axis(ax) -> None:
    ax.grid(True, alpha=0.22)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def save_accuracy_plot(path: Path, rows: list[dict]) -> None:
    plt = import_pyplot()
    epochs = [int(r["epoch"]) for r in rows]
    qp = [100.0 * r["qp_accuracy"] for r in rows]
    ponly = [100.0 * r["ponly_accuracy"] for r in rows]

    fig, ax = plt.subplots(figsize=(7.4, 4.5))
    ax.plot(epochs, qp, marker="o", linewidth=2.5, color=COLORS["qp"], label=LABELS["qp"])
    ax.plot(epochs, ponly, marker="s", linewidth=2.5, color=COLORS["ponly"], label=LABELS["ponly"])
    ax.set_title("Epoch-wise Accuracy", fontsize=14, fontweight="bold")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Accuracy (%)")
    ax.set_xticks(epochs)
    lower = max(0.0, min(qp + ponly) - 5.0)
    upper = min(100.0, max(qp + ponly) + 5.0)
    if upper - lower < 10.0:
        center = (upper + lower) / 2.0
        lower = max(0.0, center - 5.0)
        upper = min(100.0, center + 5.0)
    ax.set_ylim(lower, upper)
    style_axis(ax)
    ax.legend(frameon=False, loc="lower right")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=280, bbox_inches="tight")
    plt.close(fig)


def positive_values(values: Iterable[float | str]) -> list[float]:
    out: list[float] = []
    for value in values:
        if value == "":
            continue
        numeric = float(value)
        if numeric > 0:
            out.append(numeric)
    return out


def save_loss_plot(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    plt = import_pyplot()
    epochs = [int(r["epoch"]) for r in rows]
    qp = [r["qp_loss"] for r in rows]
    ponly = [r["ponly_loss"] for r in rows]

    fig, ax = plt.subplots(figsize=(7.4, 4.5))
    if any(v != "" for v in qp):
        ax.plot(epochs, [float(v) if v != "" else math.nan for v in qp], marker="o", linewidth=2.5, color=COLORS["qp"], label=LABELS["qp"])
    if any(v != "" for v in ponly):
        ax.plot(epochs, [float(v) if v != "" else math.nan for v in ponly], marker="s", linewidth=2.5, color=COLORS["ponly"], label=LABELS["ponly"])
    ax.set_title("Epoch-wise Training Loss", fontsize=14, fontweight="bold")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Training loss (log scale)")
    ax.set_xticks(epochs)
    values = positive_values(qp + ponly)
    if values:
        ax.set_yscale("log")
        ax.set_ylim(min(values) * 0.75, max(values) * 1.35)
    style_axis(ax)
    ax.legend(frameon=False)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=280, bbox_inches="tight")
    plt.close(fig)


def save_table_png(path: Path, rows: list[dict], fieldnames: list[str], *, title: str) -> None:
    plt = import_pyplot()
    fig_height = 1.2 + 0.46 * max(1, len(rows))
    fig, ax = plt.subplots(figsize=(9.5, fig_height))
    ax.axis("off")
    table = ax.table(
        cellText=[[row.get(field, "") for field in fieldnames] for row in rows],
        colLabels=fieldnames,
        cellLoc="center",
        colLoc="center",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9.5)
    table.scale(1, 1.35)
    for (row_idx, _col_idx), cell in table.get_celld().items():
        if row_idx == 0:
            cell.set_text_props(weight="bold", color="white")
            cell.set_facecolor("#263447")
        else:
            cell.set_facecolor("#f7f8fa" if row_idx % 2 else "white")
        cell.set_edgecolor("#d0d4da")
    ax.set_title(title, fontsize=13, fontweight="bold", pad=12)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=280, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Make final BridgePRAG paper figures and metric tables.")
    parser.add_argument("--epoch-report-dir", required=True, help="Directory containing epoch_performance.csv.")
    parser.add_argument("--qp-log", required=True)
    parser.add_argument("--ponly-log", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--max-epochs", type=int, default=None)
    args = parser.parse_args()

    epoch_report_dir = Path(args.epoch_report_dir)
    output_dir = Path(args.output_dir)
    raw_rows = read_csv_rows(epoch_report_dir / "epoch_performance.csv")
    rows = epoch_metric_rows(raw_rows)
    if args.max_epochs is not None:
        rows = [row for row in rows if int(row["epoch"]) <= args.max_epochs]
    if not rows:
        raise RuntimeError(f"No epoch rows found in {epoch_report_dir / 'epoch_performance.csv'}")

    metric_fields = [
        "epoch",
        "qp_accuracy",
        "ponly_accuracy",
        "delta_accuracy",
        "qp_token_precision",
        "ponly_token_precision",
        "delta_token_precision",
        "qp_token_recall",
        "ponly_token_recall",
        "delta_token_recall",
        "qp_token_f1",
        "ponly_token_f1",
        "delta_token_f1",
        "qp_hit",
        "ponly_hit",
        "delta_hit",
        "qp_qa_score",
        "ponly_qa_score",
        "delta_qa_score",
        "qp_time_s",
        "ponly_time_s",
    ]
    write_csv(output_dir / "paper_epoch_metrics.csv", rows, metric_fields)
    (output_dir / "paper_epoch_metrics.json").write_text(
        json.dumps({"rows": rows}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    save_accuracy_plot(output_dir / "epoch_accuracy.png", rows)

    loss_rows = merged_loss_rows(Path(args.qp_log), Path(args.ponly_log), max_epochs=args.max_epochs)
    loss_fields = ["epoch", "qp_loss", "ponly_loss", "qp_count", "ponly_count"]
    write_csv(output_dir / "epoch_loss.csv", loss_rows, loss_fields)
    save_loss_plot(output_dir / "epoch_loss.png", loss_rows)

    final_epoch = max(int(row["epoch"]) for row in rows)
    table_fields = [
        "Model",
        "Epoch",
        "Accuracy (%)",
        "Precision (%)",
        "Recall (%)",
        "Token F1 (%)",
        "Hit (%)",
        "QA Score (%)",
        "Avg. Time (s)",
    ]
    final_rows = table_rows_for_epoch(rows, final_epoch)
    write_csv(output_dir / "final_metrics_table.csv", final_rows, table_fields)
    write_markdown_table(output_dir / "final_metrics_table.md", final_rows, table_fields)
    save_table_png(output_dir / "final_metrics_table.png", final_rows, table_fields, title="Final Epoch Metrics")

    best_rows = best_table_rows(rows)
    best_fields = [
        "Model",
        "Best Epoch",
        "Accuracy (%)",
        "Precision (%)",
        "Recall (%)",
        "Token F1 (%)",
        "Hit (%)",
        "QA Score (%)",
        "Avg. Time (s)",
    ]
    write_csv(output_dir / "best_metrics_table.csv", best_rows, best_fields)
    write_markdown_table(output_dir / "best_metrics_table.md", best_rows, best_fields)
    save_table_png(output_dir / "best_metrics_table.png", best_rows, best_fields, title="Best Accuracy Metrics")

    print(f"[PRAG:paper-artifacts] accuracy plot saved: {output_dir / 'epoch_accuracy.png'}")
    print(f"[PRAG:paper-artifacts] loss plot saved: {output_dir / 'epoch_loss.png'}")
    print(f"[PRAG:paper-artifacts] final table saved: {output_dir / 'final_metrics_table.csv'}")
    print(f"[PRAG:paper-artifacts] best table saved: {output_dir / 'best_metrics_table.csv'}")


if __name__ == "__main__":
    main()
