version: '3.8'

services:
  db:
    # pgvector?띠럾? ??????뚮봽??????노뭵?? ????嶺뚯솘? ????
    image: ankane/pgvector:latest
    container_name: rag_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  # DeepFilterNet ???뚮쾳 ??蹂ㅽ깴 ??類ㅼ뮅 (numpy<2.0 ?곌랙?х뙴????삵렱)
  denoise_server:
    build: ./denoise_server
    container_name: denoise_server
    ports:
      - "8002:8002"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    restart: always

  # diart ??븐슦???釉뚯뫊????類ㅼ뮅 (?곌랙?х뙴????쳜?????? ???몃뎡 ?????怨쀬땋 ?띠럾???
  diart_server:
    build: ./diart_server
    container_name: diart_server
    ports:
      - "8003:8003"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    restart: always

  fastapi_backend:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      # Docker ??????????IP ??????類λ룴?????藥?'db')??怨쀬Ŧ DB????⑤슡???紐껊퉵??
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=postgres
      # ?筌뤾쑬裕???誘⑹굣???熬곣뫗?????筌뤿굝諭?????샑甕??????????덈뺄 繞벿살탳??Qwen????얜∥????얄뵛 ?熬곥굥??host.docker.internal ????
      - LLM_API_URL=http://host.docker.internal:11434/api/generate
      #      - DENOISE_URL=http://denoise_server:8002/denoise/raw
      - DIARIZE_URL=http://diart_server:8003/diart/raw
      - QUIZ_MOCK_MODE=false
      - SUMMARY_MOCK_MODE=false
      - LLM_URL=http://100.104.164.84:8001
      - LLM_MODEL=Qwen/Qwen2.5-3B
      - LLM_API_KEY=test-key
    depends_on:
      - db
      - diart_server
    #      - denoise_server
    volumes:
      - .:/app # ?띠룇裕녻?繞??袁⑤?獄??곌떠?????嶺뚯빖留???꾩룇瑗?????洹먮맩夷?????熬곥굥???熬곣뫗??????臾딅ご????쳜???????????? ??⑤슡??

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # ?筌뤾쑬裕?筌뤾쑴踰?node_modules?띠럾? ???쳜?????????????????? ???낆┣?????깆젧
    environment:
      - CHOKIDAR_USEPOLLING=true # Windows/WSL ???삵렱????????逾??곌떠????띠룆흮????熬곥굥???熬곣뫗????롪퍔???泥? ???깅쾳
      - VITE_BACKEND_URL=http://fastapi_backend:8000 #100.104.164.84:8000
      - VITE_BACKEND_WS_URL=ws://fastapi_backend:8000 #100.104.164.84:8000
#    depends_on:
#       - fastapi_backend
volumes:
  pgdata:
